# start uwsgi server - port: 5001

# copy uwsgi ini file to /etc/uwsgi/sites-...
# sudo service uwsgi restart?
# sudo uwsgi --ini /vagrant/config/pynet_uwsgi.ini


# set up nginx reverse proxy - port: 5000 <- 5001
# sudo rm /etc/nginx/sites-enabled/default
# sudo ln -s /vagrant/config/pynet_nginx.conf /etc/nginx/sites-enabled/
# sudo service nginx restart
# =====

- name: mysql - restart
  service:
    name: mysql
    state: restarted

- name: mysql - create user
  mysql_user:
    login_user: root
    login_password: 
    name: pynet
    password: pynet
    priv: '*.*:ALL'
    state: present

- name: mysql - check for backup
  stat: 
    path: /vagrant/config/backup.sql.bz2
  register: backup_state

- name: mysql - create database and table
  mysql_db:
    state: import
    name: all
    target: /vagrant/config/config.sql
  when: backup_state.stat.exists == False

- name: mysql - restore database and table
  mysql_db:
    state: import
    name: all
    target: /vagrant/config/backup.sql.bz2
  when: backup_state.stat.exists == True

- name: uwsgi - make pynet available
  copy:
    src: /vagrant/config/pynet_uwsgi.ini
    dest: /etc/uwsgi/apps-available/pynet_uwsgi.ini

- name: uwsgi - enable pynet
  file:
    src: /etc/uwsgi/apps-available/pynet_uwsgi.ini
    dest: /etc/uwsgi/apps-enabled/pynet_uwsgi.ini
    state: link

- name: uwsgi - restart
  service:
    name: uwsgi
    state: restarted

- name: nginx - remove default site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx - enable pynet
  file:
    src: /vagrant/config/pynet_nginx.conf
    dest: /etc/nginx/sites-enabled/pynet_nginx.conf
    state: link

- name: nginx - restart
  service:
    name: nginx
    state: restarted

