- name: restart
  service:
    name: mysql
    state: restarted

- name: create user
  mysql_user:
    login_user: root
    login_password: 
    name: pynet
    password: pynet
    priv: '*.*:ALL'
    state: present

- name: create database and table
  mysql_db:
    state: import
    name: all
    target: /vagrant/config/config.sql
