- name: apt install
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - vim
    - python3
    - python3-pip
    - python-mysqldb
    - mysql-server
#    - build-essential
 #   - python-dev
    - uwsgi-plugin-python3
    - uwsgi
    - nginx

- name: pip install
  pip:
    requirements: "{{ requirements_loc }}"
    executable: "{{ pip_exec }}"
  vars: 
    requirements_loc: /vagrant/src/requirements.txt
    pip_exec: /usr/bin/pip3

